# Generated by Django 4.1.7 on 2023-03-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(default='null', upload_to='teams', verbose_name='Foto'),
        ),
    ]
